
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREEN = 19;
  public static final int pointComa = 13;
  public static final int CanvasBackground = 5;
  public static final int CodeDraw = 2;
  public static final int coma = 14;
  public static final int parentOpen = 11;
  public static final int PINK = 22;
  public static final int BLUE = 17;
  public static final int num = 15;
  public static final int RED = 16;
  public static final int parentClose = 12;
  public static final int Square = 7;
  public static final int EOF = 0;
  public static final int keyClose = 10;
  public static final int Canvas = 3;
  public static final int ORANGE = 20;
  public static final int CYAN = 21;
  public static final int Line = 6;
  public static final int Circle = 8;
  public static final int error = 1;
  public static final int CanvasAddFigure = 4;
  public static final int YELLOW = 18;
  public static final int keyOpen = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CodeDraw",
  "Canvas",
  "CanvasAddFigure",
  "CanvasBackground",
  "Line",
  "Square",
  "Circle",
  "keyOpen",
  "keyClose",
  "parentOpen",
  "parentClose",
  "pointComa",
  "coma",
  "num",
  "RED",
  "BLUE",
  "YELLOW",
  "GREEN",
  "ORANGE",
  "CYAN",
  "PINK"
  };
}

